classDiagram
    %%Class Relationship Architecture
    GameController"1"-->"1"Game : controls

    Game"1"-->"1"Board : uses
    Game"1"-->"4"IPlayer : players
    Game"1"-->"1"Dice : uses

    Board"1"-->"52"Tile : mainTrack
    Board"1"-->"*..*"Pawn : active pawns
    IPlayer"1"-->"n"Pawn : owns
    Pawn"1"-->"1" Tile :currentTile

    %%Enumeration Class Relation
    Game..>GameState
    IPlayer..>PlayerState
    Pawn..>PawnState
    Tile..>TileType

    %%Interface
    Game-->IRuleEngine : rules
    GameController..|> IGameEvent

    class GameController{
        +Game CurrentGame
        +event ...

        +void StartGame()
        +Void RestartGame()
        +void OnDiceRolled()
        +void OnPawnMoved()
        +void OnPlayerChanged()
        +void OnPlayerWon()
    }
    class Game{
        +GameState State
        +List<Player> Players
        +Board Board
        +Dice Dice
        +Player CurrentPlayer
        +int CurrentPlayerIndex

        +IRuleEngine RuleEngine

        +void Start()
        +void Reset()
        +void End()
        +int RollDice()
        +void NextTurn()
        +Player GetCurrentPlayer()
    }
    class Board{
        +List<Tiles> MainTrack
        +Dictionary<.Player, List<Tile>> HomeStretch
        +Dictionary<.Player, Tile> StartTiles
        +Dictionary<.Player, Tile> HomeTile

        +void PlacePawn(Pawn pawn, Tile Tile)
        +void RemovePawn(Pawn pawn)
        +Tile GetTile(Pawn pawn)
        +Tile MovePawn(Pawn Pawn, int Steps)
        +void Reset()
    }
    class Dice{
        +int rollDice()
    }
    class IPlayer{
        <<Interface>>
        +String Color
        +List<Pawn> Pawns
        +PlayerState State

        +bool AllPawnsFinished()
        +pawn GetActivePawn(int roll)
    }
    class Pawn{
        +int Position
        +PawnState State
        +int StepsMoved
        +int TrackLength
        +int GoalLength

        +bool IsHome()
        +bool IsActive()
        +bool IsComplete()

    }
    class Tile{
        +TileType Type
        +Pawn OccupiedBy

        +bool isSafeZone()
        +bool isOccupied()
    }

    %%ENUMS
    class GameState{
        <<Enumeration>>
        NotStarted
        Running
        Finished
    }
    class PlayerState{
        <<Enumeration>>
        Active
        Won
    }
    class PawnState{
        <<Enumeration>>
        Home
        Active
        Complete
    }

    class TileType{
        <<enumeration>>
        Normal
        Safe
        Start
        HomeEntry
        Home
    }


    class IGameEvent{
        <<interface>>
        +event Action<.Game> GameStarted
        +event Action<.Game> GameRestart
        +event Action<.Player, int> DiceRolled
        +event Action<.Player, Piece, Tile, Tile> PawnMoved
        +event Action<.Player> PlayerChanged
        +event Action<.Player> PlayerWon
    }

    class IRuleEngine{
        <<interface>>
        +bool CanMove(Pawn pawn, int roll)
        +Tile GetDestination(Pawn pawn, int roll)
        +bool IsCapture(Tile destination)
        +bool HasPlayerWon(Player player)
    }